### ISSUE TITLE
Error message: "Illegal instruction: 4"

### ISSUE THREAD

**Issue by chrxr** [mherrmann/pypxlib#1]
When following the readme instructions, trying to run the "table = Table('db_file_path.DB')" command, I received the error message, "Illegal instruction: 4". The script then crashed.

Running on OSX, python 2.7.10

**Comment by mherrmann** [comment]
Hi,

from http://stackoverflow.com/questions/14268887/what-is-the-illegal-instruction-4-error-and-why-does-mmacosx-version-min-10 it appears that this may happen on "older" OS X versions. Which OS X version are you using?

M

**Comment by chrxr** [comment]
10.10.5 (Yosemite)

**Comment by mherrmann** [comment]
In your `lib/site-packages/pypxlib/pxlib_ctypes`, there is a file called `libpx.dylib`. Please overwrite that file with the file from the attachment below (rename `libpx.pdf` to `libpx.dylib`, GitHub doesn't allow uploading `.dylib` files). Does it now work for you?

[libpx.pdf](https://github.com/mherrmann/pypxlib/files/36486/libpx.pdf)

**Comment by chrxr** [comment]
Thanks! That worked perfectly.

**Comment by mherrmann** [comment]
Great. I released a new version (v1.6) of pypxlib to PyPI, so other users can immediately benefit from this as well.
