### ISSUE TITLE
libpx.so importerror on 32bit linux.

### ISSUE THREAD

**Issue by Craigzyc** [mherrmann/pypxlib#10]
Im getting an import error when trying to use this on a 32bit linux system. The error below happens any time I attempt to load a db file. 
The main part of the error seems to be  wrong ELF class: ELFCLASS64.
I have exhaustively searched for a fix without any luck.
Any help would be appreciated

[Error: ImportError: /usr/local/lib/python3.4/dist-packages/pypxlib/pxlib_ctypes/libpx.so: wrong ELF class: ELFCLASS64]
  traceback: 'Traceback (most recent call last):\n  File "/usr/local/lib/python3.4/dist-packages/pypxlib/pxlib_ctypes/py3.py", line 379, in load\n    return ctypes.cdll.LoadLibrary(path)\n  File "/usr/lib/python3.4/ctypes/__init__.py", line 429, in LoadLibrary\n    return self._dlltype(name)\n  File "/usr/lib/python3.4/ctypes/__init__.py", line 351, in __init__\n    self._handle = _dlopen(self._name, mode)\nOSError: /usr/local/lib/python3.4/dist-packages/pypxlib/pxlib_ctypes/libpx.so: wrong ELF class: ELFCLASS64\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "scripts/pdoxReturn.py", line 2, in <module>\n    from pypxlib import Table\n  File "/usr/local/lib/python3.4/dist-packages/pypxlib/__init__.py", line 4, in <module>\n    from pypxlib.pxlib_ctypes import *\n  File "/usr/local/lib/python3.4/dist-packages/pypxlib/pxlib_ctypes/__init__.py", line 15, in <module>\n    from pypxlib.pxlib_ctypes.py3 import *\n  File "/usr/local/lib/python3.4/dist-packages/pypxlib/pxlib_ctypes/py3.py", line 609, in <module>\n    _libs["px"] = load_library(_px_lib)\n  File "/usr/local/lib/python3.4/dist-packages/pypxlib/pxlib_ctypes/py3.py", line 365, in load_library\n    return self.load(path)\n  File "/usr/local/lib/python3.4/dist-packages/pypxlib/pxlib_ctypes/py3.py", line 381, in load\n    raise ImportError(e)\nImportError: /usr/local/lib/python3.4/dist-packages/pypxlib/pxlib_ctypes/libpx.so: wrong ELF class: ELFCLASS64\n',
  executable: '/usr/bin/python3',
  options: null,
  script: 'scripts/pdoxReturn.py',
  args: [ '--dbFile=/mnt/db/HDLastValue.DB' ],
  exitCode: 1

**Comment by mherrmann** [comment]
Only 64 bit Linux is supported at the moment. I'd be happy to accept a Pull Request that adds 32 bit support. You'd have to build pxlib according to the [instructions in the README](https://github.com/mherrmann/pypxlib#building-pxlib). Actually, to get it working on your 32 bit machine, you should be able to follow these instructions, then use the generated libpx.so to overwrite the file with the same name in pypxlib's `pxlib_ctypes` folder.

**Comment by Craigzyc** [comment]
Hi Michael,
Ive built it on the system and its working now. I didn’t realize I had to copy that file before.

I will likely be submitting a pull request to add that.

Just curious if you know anything about my next problem. Its working to read a .DB file if I copy it to the local drive but if I try to read it from a network mount it can not open the file.


Craig Zych | Controls Technician | Craig.Zych@neelands.com<mailto:Craig.Zych@neelands.com>
24 Hour Service Call: Toronto 416.798.9705 | Burlington 905.332.4555
Check out our latest news at www.neelands.com<http://www.neelands.com>

**Comment by Craigzyc** [comment]
Hi Michael,

Just wanted to let you know I worked around the limitation of not being able to read from /mnt
I just added in that if the file was on a mounted drive it first copied it to a local temp folder. This doesn’t help if I ever wanted to write but it serves my immediate needs.

Thanks for your help



Craig Zych | Controls Technician | Craig.Zych@neelands.com<mailto:Craig.Zych@neelands.com>
24 Hour Service Call: Toronto 416.798.9705 | Burlington 905.332.4555
Check out our latest news at www.neelands.com<http://www.neelands.com>

**Comment by mherrmann** [comment]
Hi,

thanks for letting me know about the problem with /mnt, and the workaround. I'll remember it if it comes up again in the future. If you still want to submit that PR for adding support for 32 bit Linux, that would be great.

Thanks,
Michael

**Comment by Craigzyc** [comment]
Hey Michael,
Any idea what would be causing the below error? For some reason I can not read datetime fields.
Ive tried a few things with no success. Just curious if you have run across this and have a solution?

traceback: 'Traceback (most recent call last):\n  File "scripts/pdoxReturn.py"
, line 63, in readTable\n    rowData[field] = row[field]\n  File "/usr/local/lib
/python3.4/dist-packages/pypxlib/__init__.py", line 266, in __getitem__\n    ret
urn field.deserialize(pxval)\n  File "/usr/local/lib/python3.4/dist-packages/pyp
xlib/__init__.py", line 139, in deserialize\n    return self._deserialize(pxval.
value)\n  File "/usr/local/lib/python3.4/dist-packages/pypxlib/__init__.py", lin
e 248, in _deserialize\n    return TimeField._deserialize(int(pxval_value.dval /
86400))\n  File "/usr/local/lib/python3.4/dist-packages/pypxlib/__init__.py", l
ine 225, in _deserialize\n    return cls._deserialize_ms(pxval_value.lval)\nAttr
ibuteError: \'int\' object has no attribute \'lval\'\n\nDuring handling of the a
bove exception, another exception occurred:\n\nTraceback (most recent call last)
:\n  File "scripts/pdoxReturn.py", line 111, in <module>\n    jsonDump = readTab
le(file)\n  File "scripts/pdoxReturn.py", line 66, in readTable\n    print(row[f
ield])\n  File "/usr/local/lib/python3.4/dist-packages/pypxlib/__init__.py", lin
e 266, in __getitem__\n    return field.deserialize(pxval)\n  File "/usr/local/l
ib/python3.4/dist-packages/pypxlib/__init__.py", line 139, in deserialize\n    r
eturn self._deserialize(pxval.value)\n  File "/usr/local/lib/python3.4/dist-pack
ages/pypxlib/__init__.py", line 248, in _deserialize\n    return TimeField._dese
rialize(int(pxval_value.dval / 86400))\n  File "/usr/local/lib/python3.4/dist-pa
ckages/pypxlib/__init__.py", line 225, in _deserialize\n    return cls._deserial
ize_ms(pxval_value.lval)\nAttributeError: \'int\' object has no attribute \'lval
\'\n',


Craig Zych | Controls Technician | Craig.Zych@neelands.com<mailto:Craig.Zych@neelands.com>
24 Hour Service Call: Toronto 416.798.9705 | Burlington 905.332.4555
Check out our latest news at www.neelands.com<http://www.neelands.com>

**Comment by mherrmann** [comment]
I refuse to try to read this garbled stack trace. Please reply on GitHub (not via email) and format the stack trace properly so I can read it.

**Comment by Craigzyc** [comment]
Sorry about that. I just copied from console.
Hopefully this is better

Traceback (most recent call last):
	File "scripts/pdoxReturn.py", line 63, in readTable    rowData[field] = row[field]
	File "/usr/local/lib/python3.4/dist-packages/pypxlib/__init__.py", line 266, in __getitem__
	return field.deserialize(pxval)  
	File "/usr/local/lib/python3.4/dist-packages/pypxlib/__init__.py", line 139, in deserialize
	return self._deserialize(pxval.value)  
	File "/usr/local/lib/python3.4/dist-packages/pypxlib/__init__.py", line 248, in _deserialize
	return TimeField._deserialize(int(pxval_value.dval /86400))
	File "/usr/local/lib/python3.4/dist-packages/pypxlib/__init__.py", line 225, in _deserialize
	return cls._deserialize_ms(pxval_value.lval)
	AttributeError: \'int\' object has no attribute \'lval\'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
	File "scripts/pdoxReturn.py", line 111, in <module>
	jsonDump = readTable(file)
	File "scripts/pdoxReturn.py", line 66, in readTable
	print(row[field])
	File "/usr/local/lib/python3.4/dist-packages/pypxlib/__init__.py", line 266, in __getitem__
	return field.deserialize(pxval)
	File "/usr/local/lib/python3.4/dist-packages/pypxlib/__init__.py", line 139, in deserialize
	return self._deserialize(pxval.value)
	File "/usr/local/lib/python3.4/dist-packages/pypxlib/__init__.py", line 248, in _deserialize
	return TimeField._deserialize(int(pxval_value.dval / 86400))
	File "/usr/local/lib/python3.4/dist-packages/pypxlib/__init__.py", line 225, in _deserialize
	return cls._deserialize_ms(pxval_value.lval)\nAttributeError: \'int\' object has no attribute \'lval'

**Comment by mattbaker-digital** [comment]
Fixed in release 2.4
