### ISSUE TITLE
how to install this library?

### ISSUE THREAD

**Issue by vinnyparker** [mherrmann/pypxlib#11]
Hi, I'm not a python programmer, But,  i'd like to install this library to run a script that uses it. And I dont know how to do it. I'm using Python 3.5.4 on Sabayon linux. I run pip install... but I havent pip installed. If you could tell me how, I'll be very very thankfull

**Comment by mherrmann** [comment]
Hi, I'm sorry I don't have time to help with this. But I highly recommend asking your question at stackoverflow.com. That site specializes in questions such as the one you asked.
