### ISSUE TITLE
try... except masking an Import Error

### ISSUE THREAD

**Issue by keisetsu** [mherrmann/pypxlib#2]
I'm really excited about this library: our whole company is dependent on Paradox, and this looks like it may give us a chance to do some interesting things with it.

I'm using pypxlib 1.6, python 3.4.2, pxlib 0.6.5 on Ubuntu 15-04.

I noticed that every date field was returning an error. I delved into the code a bit, and noticed that you are not importing datetime, but there aren't errors reported. In fact, around line 256 you have an except that catches and ignores all errors. It catches the ImportError, so there's no way to tell what's going on.

I put in a raise right after the except to find the error; I imported datetime, but received another error, this time about an invalid type. I believe you need to use c_int.value for the DateField class's _deserialize:

```
return datetime.date(year.value, month.value, day.value)
```

After this the dates are true python datetime.date types!

Pretty simple stuff, but if you want, I can try to put in a pull request after I play with the library a bit more.

**Comment by mherrmann** [comment]
Hi, thanks for letting me know! I'm glad you appreciate the library :) If you can, it would be great if you submit a pull request as that makes it most clear which changes are required.
Cheers
M
