### ISSUE TITLE
ImportError: px_x64 not found.

### ISSUE THREAD

**Issue by jmcarter17** [mherrmann/pypxlib#21]
I have installed pxlib and pypxlib.
I have checked that pxlib is working by writing a small c program that uses it, and it seems to work.
However, when I try to use pypxlib, when importing Table, I get the following error:

```
>>> from pypxlib import Table
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/site-packages/pypxlib/__init__.py", line 4, in <module>
    from pypxlib.pxlib_ctypes import *
  File "/usr/local/lib/python3.7/site-packages/pypxlib/pxlib_ctypes/__init__.py", line 15, in <module>
    from pypxlib.pxlib_ctypes.py3 import *
  File "/usr/local/lib/python3.7/site-packages/pypxlib/pxlib_ctypes/py3.py", line 617, in <module>
    _libs["px"] = load_library(_px_lib)
  File "/usr/local/lib/python3.7/site-packages/pypxlib/pxlib_ctypes/py3.py", line 367, in load_library
    raise ImportError("%s not found." % libname)
ImportError: px_x64 not found.
>>> 
```

Any ideas? 
Thanks.

**Comment by jmcarter17** [comment]
P.S. I get the exact same error in macOS and in ubuntu ...

**Comment by mherrmann** [comment]
Could this be a result of your PR @mattbaker-digital?

**Comment by mattbaker-digital** [comment]
@mherrmann, most likely. I will have a look and let you know. I did test on Windows and Ubuntu so not sure why.

**Comment by mherrmann** [comment]
Thanks!

**Comment by mattbaker-digital** [comment]
@mherrmann I've installed pypxlib 2.4 and it's missing from the pxlib_ctypes directory:
- libpx_x64.so
- libpx_x64.dylib

**Comment by mherrmann** [comment]
All I did was merge your PR. Then these files must have been missing there.

**Comment by mherrmann** [comment]
(Hope this doesn't sound accusing; It's not meant to be. I'm just stating what I perceive as facts, to help us find a solution.)

**Comment by mattbaker-digital** [comment]
The merge contains the files in the repo

> 
> 
> (Hope this doesn't sound accusing; It's not meant to be. I'm just stating what I perceive as facts, to help us find a solution.)

Don't worry. Likewise.

**Comment by mattbaker-digital** [comment]
Are there any other files that need updating when package is released to mark as include?

**Comment by mherrmann** [comment]
Good point. I think you may need to update `setup.py`, sorry.

**Comment by mattbaker-digital** [comment]
I've never done anything package related before, so will remember that for next time.
Shall I update the file?

**Comment by jmcarter17** [comment]
Wow thanks guys for looking into it so quickly ...
Should I retry?
From your conversation, it looks like the pxlib doesn't need to be installed locally? That you package it with the library? Or am I misinterpreting this conversation?

**Comment by mattbaker-digital** [comment]
It's still waiting for the changes to be merged back into the main repo at the moment.
You're correct, the compiled pxlib library is bundled with pypxlib.
For a quick fix you could either:
- copy the missing files `libpx_x64.dylib` and `libpx_x64.so` to where the packaged was installed (https://stackoverflow.com/a/122340/5683049) + pypxlib/pxlib_ctypes
- clone/download https://github.com/mattbaker-digital/pypxlib and use `pip install -e <location of downloaded pypxlib>`

**Comment by mherrmann** [comment]
Thank you for the fix @mattbaker-digital. I uploaded a new version 2.5 to PyPI.

**Comment by jmcarter17** [comment]
Thanks guys, works great.
