### ISSUE TITLE
Stack Smashing Detected

### ISSUE THREAD

**Issue by caleidos** [mherrmann/pypxlib#26]
Hi, i have a simple simple code to convert the Paradox db to a dictionary and save in a .dat with picke. 

In Windows all works great but in Ubuntu 20 server and venv for python 3.8 i have this issue.

 *** stack smashing detected ***: terminated
Aborted (core dumped)

This is the error with my code. 

from pypxlib import Table
table = Table("/complete/path/database.DB")
for x in table:
    print(x)

THAKS for your work. With this tool i can take the database of paradox and convert it to mongoDB to work faster and populate the data of my company THANKS A LOT 

How can i contribute to the proyect ?

**Comment by mherrmann** [comment]
You're welcome :-) Regarding your question:

> How can i contribute to the proyect ?

Fix the issue you are experiencing above and submit a Pull Request so others can benefit from your fix :-)

**Comment by caleidos** [comment]
Sorry, I don't have the knowledge to fix it. Have some suggest about it ?

**Comment by mherrmann** [comment]
I don't have an idea, sorry.
