### ISSUE TITLE
Could not read blob data

### ISSUE THREAD

**Issue by denisroldan** [mherrmann/pypxlib#5]
First of all, thanks for this fantastic library! Awesome work 👍 👍 👍 

I'm having troubles retrieving blob fields. Some of my tables have blob fields inside, and calling: `print(table.fields` I can see the field interpreted as: `<pypxlib.BytesField object at 0x1014b3358>`
Sounds good, but when I try to retrieve the data of a row with that field filled, it returns:

`Row(FIELD_1=392, FIELD_2=3,  BLOB_FIELD='<error>')`
`PXLib: Could not read blob data.`

But the field is OK apparently. If I use the freeware "dBase Paradox Reader" on Windows, I can see correctly the data using the following encodings:

Input:

> cp850

Output:

> latin_1 (Western)

But I tried on Python using pyxlib and specifying the encoding with:
`table = Table('my_database.db', encoding='latin_1')`
`table = Table('my_database.db', encoding='utf_8')`
`table = Table('my_database.db', encoding='cp850')`

And I get the same error. I also tried to do something more "low-level"  and I can't get it running:

``` python
from pypxlib.pxlib_ctypes import *
from ctypes import POINTER
pxdoc = PX_new()
PX_open_file(pxdoc, b"data/myDatabase.db")
num_fields = PX_get_num_fields(pxdoc)
print('test.db has %d fields:' % num_fields)
offset = c_int()
blobdata = c_char()
data = c_char()
mod_nr = c_int()
size = c_int()
for i in range(num_fields):
    field = PX_get_field(pxdoc, i)
    if field.contents.px_fname == "HISTORIAL":
        PX_get_data_blob(pxdoc, POINTER(data), field.contents.px_flen, POINTER(mod_nr), POINTER(size), POINTER(POINTER(blobdata)))
    offset.value = offset.value + field.contents.px_flen
#Close the file:
PX_close(pxdoc)
#Free the memory associated with pxdoc:
PX_delete(pxdoc)
```

What's the problem? Any clue will be VERY useful.

I'm using **OSX 10.11.4** and I tried with both **Python2 and Python3**.

Thanks

**Comment by mherrmann** [comment]
Hi,

I'm sorry I don't know what the reason for this is. The documentation for pxlib [says](http://pxlib.sourceforge.net/documentation.php?manpage=PX_get_data_blob) that `PX_get_data_blob` is obsolete and `PX_retrieve_record` should be used instead. Maybe that would work?

Regards
Michael

**Comment by denisroldan** [comment]
Unfortunately I tried with `PX_retrieve_record` and I can't retrieve the data :( 

Here's the DB I'm working with: [ExampleDB.zip](https://github.com/mherrmann/pypxlib/files/231528/ExampleDB.zip)

The BLOB field "INCIDENCIAS" (null in almost every row) is unreadable in the rows where the field is not empty. 😢 

I'll keep watching the repo if someone finds a solution hehe.

**Comment by hrompato** [comment]
Denis, te escribo en Español que es más fácil.

Tengo código en Qt que lee algunas tablas Paradox y he visto ese error pero tampoco encuentro el inconveniente ya que cuando depuro, desaparece.
Si embargo observé que no se pierde ningún dato.

De cualquier manera te aclaro que esto es Qt, no la librería Python, por si te sirve:

```
ui->recCount->clear();
ui->recCount->setText(QString::number(cuenta));
for (int x = 0; x < cuenta; x++) {
    qDebug() << "Datos del registro:" << QString::number(x);
    pxval_t **registro = tabla.leeRegistro(x);
    for (int n = 0; n < num_fields; n++) {
        if (!registro[n]->isnull)
        {
            long valorL = 0L;
            double valorD = 0.0;
            QString alpha;
            QByteArray memo;
            int tipo = registro[n]->type;
            int tamanio;
            switch (tipo) {
            case pxfShort:
                valorL = registro[n]->value.lval;
                qDebug() << lista.at(n) << ":\t" << QString::number(valorL);
                break;
            case pxfLong:
                valorL = registro[n]->value.lval;
                qDebug() << lista.at(n) << ":\t" << QString::number(valorL);
                break;
            case pxfDate:
                valorL = registro[n]->value.lval;
                qDebug() << lista.at(n) << "\t:" << QString(PX_date2string(tabla.get_PX_doc(), valorL, "d/m/Y"));
                QDate::fromString(QString(PX_date2string(tabla.get_PX_doc(), valorL, "d/m/Y")));
                break;
            case pxfTime:
                valorL = registro[n]->value.lval;
                qDebug() << lista.at(n) << "\t:" << QString(PX_time2string(tabla.get_PX_doc(), valorL, "H:i:s"));
                QTime::fromString(QString(PX_time2string(tabla.get_PX_doc(), valorL, "H:i:s")));
                break;
            case pxfLogical:
                valorL = registro[n]->value.lval;
                qDebug() << lista.at(n) << "\t:" << QString::number(valorL);
                break;
            case pxfAutoInc:
                valorL = registro[n]->value.lval;
                qDebug() << lista.at(n) << "\t:" << QString::number(valorL);
                break;
            case pxfTimestamp:
                valorD = registro[n]->value.dval;
                qDebug() << lista.at(n) << "\t:" << QString(PX_timestamp2string(tabla.get_PX_doc(), valorD, "d/m/Y H:i:s"));
                QDateTime::fromString(QString(PX_timestamp2string(tabla.get_PX_doc(), valorD, "d/m/Y H:i:s")));
                break;
            case pxfNumber:
                valorD = registro[n]->value.dval;
                qDebug() << lista.at(n) << "\t:" << QString::number(valorD);
                break;
            case pxfCurrency:
                valorD = registro[n]->value.dval;
                qDebug() << lista.at(n) << "\t:" << QString::number(valorD);
                break;
            case pxfAlpha:
                alpha = QString::fromLatin1(registro[n]->value.str.val);
                qDebug() << lista.at(n) << "\t:" << alpha;
                break;
            case pxfMemoBLOb:
                tamanio = registro[n]->value.str.len;
                memo.resize(tamanio);
                memo = registro[n]->value.str.val;
                qDebug() << lista.at(n) << "\t:" << QString::fromLatin1(memo);
                break;
            default:
                qDebug() << lista.at(n) << "in tipo conocido:" << tipo;
                break;
            }
        }
        else
        {
            qDebug() << lista.at(n) << ": Vacío";
        }
    }
```

**Comment by denisroldan** [comment]
Wow! Muchísimas gracias @hrompato!!! Probaré con Qt esta semana y en cuanto sepa algo te digo. Gracias de veras!!!

**Comment by hrompato** [comment]
Denis, algo más que pude observar. Si los BLOBs pueden estar en un archivo .MB, entonces es necesario abrir el mismo usando la función PX_set_blob_file
Para usar la misma es necesario abrir primero el archivo .DB y pasar el px_doc a dicha función

```
PX_boot();
datos = PX_new();
if (datos) {
    if (PX_open_file(datos, database->toStdString().data()) == 0) {
        // Intento abrir archivo MB si es que tiene blobs
        QString blob(database->data());
        blob.replace(".db", ".mb");
        QFile blob_file(blob);
        if (blob_file.exists()) {
            int estado = PX_set_blob_file(datos, blob.toStdString().data());
            if (estado == 0) {
                rv = "OK";
                return;
            }
            else {
                rv = "Error leyendo archivo blob";
                return;
            }
        }
        rv = "OK";
        return;
    }
    else {
        rv = "Error leyendo archivo: ";
        rv.append(database);
        return;
    }
}
else
{
    rv = "Error generando datos";
    return;
}
```

Espero haber sido claro

Saludos

**Comment by denisroldan** [comment]
Hola Héctor (@hrompato)!

¡¡Definitivamente me abriste los ojos con ambos scripts!!  Culpa mía de no haberme leído a fondo las documentaciones de la librería en C.  Sobretodo donde ponía... "deprecated" y "obsolete" 😈 

Te debo unas buenas 🍻 

@mherrmann I'm currently working on a workaround to support external blobfiles. You'll have a pull request asap.

Thank you guys!

**Comment by mherrmann** [comment]
@denisroldan can this issue be closed now that your PR has been merged?

**Comment by denisroldan** [comment]
Of course! Thank you again 😀

**Comment by Das332021** [comment]
I need to access to the data in the paradox table to read and write .
In the first part i tried to acces to the paradox data base with this method but it gives me error:

from pypxlib import Table table = Table(r'data base path') print(table.fields)

it return an error:
print(table.fields)
field_name = field.px_fname.data.decode(self.px_encoding, self.px_decode_errors)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe9 in position 3: ordinal not in range(128)

Then i tried this method it works but i need to access to the data .That's the code and i tried with PX_get_data_blob but i didn't understand what parameters i should put .

Please can someone help me and thank you in advance.

`from pypxlib.pxlib_ctypes import *
DB = PX_new()
PX_open_file(DB, b"data base path")

num_fields = PX_get_num_fields(DB)
print(num_fields)

for i in range(num_fields):
field = PX_get_field(DB, i)
print(field.contents.px_fname)

Close the file:
PX_close(DB)

Free the memory associated with pxdoc:
PX_delete(DB)`

**Comment by mherrmann** [comment]
@Das332021 please don't spam this forum by posting the exact same text in multiple places.

**Comment by Das332021** [comment]
@mherrmann ok sorry for that.

**Comment by hrompato** [comment]
> I need to access to the data in the paradox table to read and write .
> In the first part i tried to acces to the paradox data base with this method but it gives me error:
> 
> from pypxlib import Table table = Table(r'data base path') print(table.fields)
> 
> it return an error:
> print(table.fields)
> field_name = field.px_fname.data.decode(self.px_encoding, self.px_decode_errors)
> UnicodeDecodeError: 'ascii' codec can't decode byte 0xe9 in position 3: ordinal not in range(128)
> 
> Then i tried this method it works but i need to access to the data .That's the code and i tried with PX_get_data_blob but i didn't understand what parameters i should put .
> 
> Please can someone help me and thank you in advance.
> 
> `from pypxlib.pxlib_ctypes import *
> DB = PX_new()
> PX_open_file(DB, b"data base path")
> 
> num_fields = PX_get_num_fields(DB)
> print(num_fields)
> 
> for i in range(num_fields):
> field = PX_get_field(DB, i)
> print(field.contents.px_fname)
> 
> Close the file:
> PX_close(DB)
> 
> Free the memory associated with pxdoc:
> PX_delete(DB)`

Te voy a responder en español. Quizás tengas que buscar con qué codificación se generaron los datos, en mi caso (usando Qt) los datos estaban guardados en codificación "Windows-1252" y yo usé un objeto 
QTextCodec *codec = QTextCodec::codecForName("Windows-1252");

Parecería que tenés que convertir el string devuelto antes

**Comment by Das332021** [comment]
@hrompato thank you so much for your comment .
I will try to do it .

**Comment by Das332021** [comment]
@hrompato it doesn't work .

**Comment by hrompato** [comment]
> @hrompato it doesn't work .

El archivo 'blob' debe existir para que puedas acceder al mismo, si no existe los datos están en el archivo .MB

Quizás debas leer primero ésta página: http://pxlib.sourceforge.net/
